version: '3'
services:
  postgres_db:
    image: postgres:alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: labrinth
      POSTGRES_PASSWORD: labrinth
      POSTGRES_HOST_AUTH_METHOD: trust
  meilisearch:
    image: getmeili/meilisearch:v0.19.0
    restart: on-failure
    ports:
      - "7700:7700"
    volumes:
      - meilisearch-data:/data.ms
    environment:
      MEILI_MASTER_KEY: modrinth
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@modrinth.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "8070:80"
    volumes:
      - ./pgadmin_default_servers.json:/pgadmin4/servers.json
volumes:
  meilisearch-data:
  db-data:
