apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: routes
spec:
  parentRefs:
    - name: main-gateway
      namespace: ${GATEWAY_NAMESPACE}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /_internal/billing
        - path:
            type: Exact
            value: /_internal/_stripe
      backendRefs:
        - name: billing-labrinth
          port: 80
