[package]
name = "path-util"
edition.workspace = true

[dependencies]
typed-path.workspace = true
serde.workspace = true
derive_more = { workspace = true, features = ["display", "deref"] }
itertools.workspace = true

[lints]
workspace = true
