apiVersion: kustomize.config.k8s.io/v1beta1
kind: Component
images:
  - name: labrinth
    newName: modrinth.local/labrinth # Change with your local build of labrinth or a remote image build (like ghcr.io/modrinth/labrinth:main)
    newTag: latest