[package]
name = "muralpay"
version = "0.1.0"
edition.workspace = true
description = "Mural Pay API"
license = "MIT"
keywords = []
categories = ["api-bindings"]

[dependencies]
arc-swap = { workspace = true, optional = true }
bytes = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
derive_more = { workspace = true, features = [
  "deref",
  "display",
  "error",
  "from",
] }
reqwest = { workspace = true, features = ["default-tls", "http2", "json"], optional = true }
rust_decimal = { workspace = true, features = ["macros", "serde-with-float"] }
rust_iso3166 = { workspace = true }
secrecy = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_with = { workspace = true }
strum = { workspace = true, features = ["derive"] }
utoipa = { workspace = true, features = ["chrono", "decimal", "uuid"], optional = true }
uuid = { workspace = true, features = ["serde"] }

[features]
client = ["dep:reqwest", "dep:secrecy"]
mock = ["dep:arc-swap"]
utoipa = ["dep:utoipa"]

[lints]
workspace = true
