apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: routes
spec:
  parentRefs:
    - name: main-gateway
      namespace: ${GATEWAY_NAMESPACE}
  rules:
    - matches:
        - path:
            type: Exact
            value: /v3/teams
        - path:
            type: Exact
            value: /v2/teams
      backendRefs:
        - name: teams-labrinth
          port: 80
