apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: routes
spec:
  parentRefs:
    - name: main-gateway
      namespace: ${GATEWAY_NAMESPACE}
  rules:
    - matches:
        - path:
            type: Exact
            value: /v3/user
        - path:
            type: Exact
            value: /v2/user
        - path:
            type: PathPrefix
            value: /_internal/auth
        - path:
            type: PathPrefix
            value: /_internal/oauth
      backendRefs:
        - name: auth-labrinth
          port: 80