[package]
name = "modrinth-log"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
dotenvy = { workspace = true }
eyre = { workspace = true }
sentry = { workspace = true, optional = true, features = ["tracing"] }
tracing = { workspace = true }
tracing-ecs = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
sentry = ["dep:sentry"]

[lints]
workspace = true
