[package]
name = "modrinth-util"
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
actix-web = { workspace = true }
derive_more = { workspace = true, features = ["display", "error", "from"] }
dotenvy = { workspace = true }
eyre = { workspace = true }
modrinth-log = { workspace = true }
rust_decimal = { workspace = true, features = ["macros"], optional = true }
serde = { workspace = true, features = ["derive"] }
utoipa = { workspace = true, optional = true }

[dev-dependencies]
serde_json = { workspace = true }

[features]
decimal = ["dep:rust_decimal", "utoipa?/decimal"]
utoipa = ["dep:utoipa"]

[lints]
workspace = true
