name: Coverage-Tarpaulin

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

on:
  push:
    branches: [ master ]
  # Uncomment to allow PRs to trigger the workflow
  # pull_request:
  #   branches: [ master ]
jobs:
  citarp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Start Docker Compose
      - name: Start Docker Compose
        run: docker-compose up -d

      - name: Install cargo tarpaulin
        uses: taiki-e/install-action@cargo-tarpaulin
      - name: Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --timeout 120 --out xml
        env:
          BACKBLAZE_BUCKET_ID: ${{ secrets.BACKBLAZE_BUCKET_ID }}
          BACKBLAZE_KEY: ${{ secrets.BACKBLAZE_KEY }}
          BACKBLAZE_KEY_ID: ${{ secrets.BACKBLAZE_KEY_ID }}
          S3_ACCESS_TOKEN: ${{ secrets.S3_ACCESS_TOKEN }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_URL: ${{ secrets.S3_URL }}
          S3_REGION: ${{ secrets.S3_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          SQLX_OFFLINE: true
          DATABASE_URL: postgresql://labrinth:labrinth@localhost/postgres

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v2
        with:
          # token: ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error: true
