name: daedalus-docker-build

on:
  push:
    branches:
      - '**'
    paths:
      - .github/workflows/daedalus-docker.yml
      - 'apps/daedalus_client/**'
      - 'packages/daedalus/**'
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/daedalus-docker.yml
      - 'apps/daedalus_client/**'
      - 'packages/daedalus/**'
  merge_group:
    types: [checks_requested]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Check out code
        uses: actions/checkout@v4

      - name: ğŸ§° Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: âš™ï¸ Generate Docker image metadata
        id: docker_meta
        uses: docker/metadata-action@v5
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ghcr.io/modrinth/daedalus
          labels: |
            org.opencontainers.image.title=daedalus
            org.opencontainers.image.description=Modrinth game metadata query client
            org.opencontainers.image.licenses=MIT
          annotations: |
            org.opencontainers.image.title=daedalus
            org.opencontainers.image.description=Modrinth game metadata query client
            org.opencontainers.image.licenses=MIT

      - name: ğŸ”‘ Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ”¨ Build and push
        uses: docker/build-push-action@v6
        with:
          file: ./apps/daedalus_client/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          cache-from: type=registry,ref=ghcr.io/modrinth/daedalus:main
          cache-to: type=inline
